# These define the epoch range for the model to cover. 
# If left blank the component will use the range it was 
# previously configured with, either at start-up or in the last call
time start_range
time end_range
---
bool success
---
string result