string action_server
geometry_msgs/PoseStamped target_pose
---
string outcome #'succeeded', 'preempted', 'planner_failure', 'monitor1_failure', ..., 'monitorn_failure'
bool recovered
bool human_interaction
---
