string action_server
geometry_msgs/PoseStamped target_pose
---
uint8 SUCCEEDED=0
uint8 BUMPER_FAILURE=1
uint8 LOCAL_PLANNER_FAILURE=2
uint8 GLOBAL_PLANNER_FAILURE=3
uint8 PREEMPTED=4
uint8 sm_outcome
---
