#all vectors should have the same length. monitor_class must be of class monitored_navigation.monitor_state.MonitorState and recovery_class of class monitored_navigation.recover_state_machine.RecoverStateMachine
string[] names
strands_navigation_msgs/DynClassLoaderDef[] monitor_states
strands_navigation_msgs/DynClassLoaderDef[] recovery_state_machines
---
bool success